### ISSUE TITLE
Add experiment_id as a field in the Trailguide dashboard UI

### ISSUE THREAD

**Issue by pcarolan** [markrebec/trailguide#1]
**Feature Request**

In order to precisely identify unique experiments in our codebase and in enabled tracking and logging, it would be helpful to have the experiment_id displayed in the Trailguide UI dashboard. Today, the descriptive title is displayed which does not always align with the experiment_id set by the developer.

**Comment by markrebec** [comment]
Hey Pat! I'm spending a little time polishing things off for a 1.0 release, and wanted to circle back on this. Can you remind me, was this the idea we discussed a while back of an experiment key + a started at timestamp as an identifier, correct? Something like `my_cool_experiment-1567103545` to more easily identify specific experiment runs in third party analytics.

Or are you just referring to displaying the raw experiment name (`my_cool_experiment`) vs the "titleized" name ("My Cool Experiment")?

I **think** back when this issue was filed, we ended up implementing the name+timestamp logic on the application side, within the custom TrailGuide callbacks we were defining, by concatenating the ID together when sending analytics tracks.

TrailGuide currently does not have a concept of a unique ID per experiment *run*, which means it'd be tough to accurately reference those same custom IDs being used in your application tracking. However, the idea of an "experiment run ID" - essentially the same thing, name+timestamp - feels like something that might be worth codifying here in the engine, and would make it possible to accurately display in the admin UI.

Keep an eye on this issue for updates, or if you have any other thoughts feel free to chime in here.
